var keys = {
  photoshop : {
      mac : {
        "start help" : "Help key",
        "Undo" : "Command + Z",
        "redo" :	"Command + Y",
        "cut" :	"Command + X",
        "copy" :	"Command + C",
        "paste" :	"Command + V",
        "show/hide brush panel" :	"F5",
        "color panel" :	"F6",
        "layers panel" :	"F7",
        "info panel" :	"F8",
        "actions panel" :	"Option + F9",
        "revert" :	"F12",
        "fill" :	"Shift + F5",
        "feather selection" :	"Shift + F6",
        "inverse selection" :	"Command + Shift + I",
        "move tool"	: "V",
        "marquee tool" :	"M",
        "lasso tool" :	"L",
        "magic wand" :	"W",
        "crop tool" :	"C",
        "eyedropper tool" :	"I",
        "spot healing" :	"J",
        "brush tool"	:"B",
        "clone stamp tool" :	"S",
        "history brush tool" :	"Y",
        "eraser tool" :	"E",
        "gradient tool" :	"G",
        "dodge tool" :	"O",
        "pen tool" : "P",
        "type tool" :	"T",
        "direct Selection tool" :	"A",
        "shape tool" :	"U",
        "hand tool" :	"H",
        "rotate View tool" :	"R",
        "zoom tool" :	"Z"
            },
      windows : {
        "start help"	:	"F1",
        "undo"	:	"Ctrl + Z",
        "redo"	:	"Ctrl + Y",
        "cut"	:	"Ctrl + X",
        "copy"	: "Ctrl + C",
        "paste"	:	"Ctrl + V",
        "show/hide brush panel"	:	"F5",
        "color panel"	:	"F6",
        "layers panel"	:	"F7",
        "info panel"	:	"F8",
        "actions panel"	:	"F9",
        "revert"	:	"F12",
        "fill"	:	"Shift + F5",
        "feather selection"	:	"Shift + F6",
        "inverse selection"	:	"Ctrl + Shift + I",
        "move tool"	:	"V",
        "marquee tool"	:	"M",
        "lasso tool"	:	"L",
        "magic wand"	:	"W",
        "crop tool"	:	"C",
        "eyedropper tool"	:	"I",
        "spot healing"	:	"J"
        "brush tool"	:	"B",
        "clone stamp tool"	:	"S",
        "history brush tool"	:	"Y",
        "eraser tool"	:	"E",
        "gradient tool"	:	"G",
        "dodge tool"	:	"O"
        "pen tool"	:	"P"
        "type tool"	:	"T"
        "direct selection tool"	:	"A"
        "shape tool"	:	"U",
        "hand tool"	:	"H",
        "rotate view tool"	:	"R",
        "zoom tool"	:	"Z"
      }
  }
}
